
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    restart: always
    depends_on:
      - db
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev

  ldap:
    image: osixia/openldap:latest
    container_name: openldap
    restart: always
    environment:
      LDAP_ORGANISATION: "MyCompany"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_TLS: "false"


    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap-data:/var/lib/ldap   # Stockage des données LDAP
      - ldap-config:/etc/ldap     # Stockage des configurations LDAP



  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_ALLOW_ANONYMOUS: "TRUE"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8090:80"
    depends_on:
      - ldap




volumes:
  local_pgdata:
  pgadmin-data:
  ldap-data:
  ldap-config:




