spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
              - X-Tenant-ID
            allowCredentials: true
      routes:
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1


  main:
    web-application-type: reactive
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      metadata-map:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 8082
